version: '3.1'
services:
  db:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
  odoo:
    build:
      context: .
      dockerfile: odoo/Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    networks:
      - mynetwork
networks:
  mynetwork:
